[package]
name = "differ"
version = "0.2.0"
authors = ["Kissbug8720 <kissbug8720@gmail.com>"]
edition = "2024"

[dependencies]
md5 = "0.8"
twox-hash = "2.0"
serde_json = "1.0"
walkdir = "2"
zip = "6.0"
colored = "3.0"

[features]
flate2 = []
bzip2 = []
